#!/bin/sh

# directories of the JS files
JS_DIR='yithwebclient/static/js'

# this is the path to the final combined file that you want to have in the end
JS_COMBINED_FILE="$JS_DIR/yith.min.js"

# These files are your JS files you want to combine together
JS_APPEND_FILES=( libs/jquery-1.7.2.min.js libs/bootstrap.min.js libs/sjcl.js )
JS_FILES=( libs/ember-1.0.0-rc.1.js libs/pwstrength.js app.js )

JS_TEMP="$JS_DIR/_yith.min.js"

# clear the file
> $JS_COMBINED_FILE

# run thru the append JS files
for F in ${JS_APPEND_FILES[@]}; do
    cat "$JS_DIR/$F" >> $JS_COMBINED_FILE
    echo "
" >> $JS_COMBINED_FILE
done

# run thru the JS files
for F in ${JS_FILES[@]}; do
    cat "$JS_DIR/$F" >> $JS_TEMP
    echo "
" >> $JS_TEMP
done

# compress it
uglifyjs $JS_TEMP >> $JS_COMBINED_FILE

# remove the temp files
rm $JS_TEMP

# add the file to the git base
git add $JS_COMBINED_FILE

echo "JS compressed"
