#!/bin/sh

# directories of the JS files
JS_DIR='yithwebclient/static/js'

# this is the path to the final combined file that you want to have in the end
JS_COMBINED_FILE="$JS_DIR/yith.min.js"

# These files are your JS files you want to combine together
JS_APPEND_FILES=( libs/jquery-2.0.3.min.js libs/bootstrap.min.js libs/sjcl.js )
JS_FILES=( libs/handlebars-1.0.0.js libs/ember.prod-1.0.0.js libs/ember-data.prod-1.0.0-beta.2.js libs/pwstrength-bootstrap-1.0.2.js app.js objects.js models.js controllers.js views.js )

JS_TEMP="$JS_DIR/_yith.min.js"

# clear the file
> $JS_COMBINED_FILE

# run thru the append JS files
for F in ${JS_APPEND_FILES[@]}; do
    cat "$JS_DIR/$F" >> $JS_COMBINED_FILE
    echo "
" >> $JS_COMBINED_FILE
done

# run thru the JS files
for F in ${JS_FILES[@]}; do
    cat "$JS_DIR/$F" >> $JS_TEMP
    echo "
" >> $JS_TEMP
done

# compress it
uglifyjs $JS_TEMP >> $JS_COMBINED_FILE

# remove the temp files
rm $JS_TEMP

echo "JS compressed"
